name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

permissions:
  contents: read

jobs:
  Test:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run AL-Go Actions Tests
        run: |
          . (Join-Path "." "Tests/runtests.ps1") -Path "Tests"

      - name: Test AL-Go Workflows
        if: github.repository_owner == 'microsoft'
        run: |
          . (Join-Path "." "Tests/runtests.ps1") -Path "Tests/WorkflowSanitation"

      - name: Test aka.ms links in markdown files
        if: github.repository_owner == 'microsoft'
        run: |
          . (Join-Path "." "Tests/runtests.ps1") -Path "Tests/MarkdownLinks"
